# Generated by Django 5.1.6 on 2025-03-24 08:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VegetableAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_type', models.CharField(choices=[('add_vegetable', 'Add Vegetable'), ('update_price', 'Update Price'), ('deactivate_vegetable', 'Deactivate Vegetable')], max_length=100)),
                ('vegetable_name', models.CharField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('details', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('img', models.ImageField(upload_to='veg_images')),
                ('tran_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriceMonitor.vegetableaction')),
            ],
        ),
    ]
