# Generated by Django 5.1.6 on 2025-03-25 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceMonitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vegetableaction',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
