# Generated by Django 5.1.6 on 2025-03-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceMonitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vegetable',
            name='loc_id',
            field=models.IntegerField(null=True),
        ),
    ]
