# Generated by Django 5.1.6 on 2025-03-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceMonitor', '0002_vegetable_loc_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vegetable',
            name='loc_id',
        ),
        migrations.RemoveField(
            model_name='vegetable',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vegetable',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='vegetable',
            name='tran_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
