# Generated by Django 5.1.6 on 2025-03-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceMonitor', '0003_remove_vegetable_loc_id_remove_vegetable_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegetable_id', models.IntegerField()),
                ('location_id', models.IntegerField()),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=1000)),
                ('location_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=255)),
            ],
        ),
    ]
