# Generated by Django 5.1.6 on 2025-03-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceMonitor', '0004_pricehistory_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tran_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='location_id',
            field=models.IntegerField(null=True),
        ),
    ]
