# Generated by Django 5.1.6 on 2025-03-12 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceMonitor', '0005_transaction_tran_type_alter_transaction_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tran_type',
            field=models.CharField(choices=[('add_vegetable', 'Add Vegetable'), ('update_price', 'Update Price'), ('add_user', 'Add User')], max_length=100),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='tran_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='PriceMonitor.transaction'),
        ),
    ]
