# Generated by Django 5.1.6 on 2025-03-13 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceMonitor', '0006_alter_transaction_tran_type_alter_vegetable_tran_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegetable',
            name='tran_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PriceMonitor.transaction'),
        ),
    ]
