# Generated by Django 5.1.6 on 2025-03-19 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceMonitor', '0007_alter_vegetable_tran_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_method', models.CharField(max_length=10)),
                ('request_path', models.CharField(max_length=1000)),
                ('request_body', models.CharField(max_length=1000)),
                ('response_status', models.IntegerField()),
                ('response_body', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PriceHistory',
        ),
        migrations.AddField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AddField(
            model_name='transaction',
            name='vegetable_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vegetable',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
