# Generated by Django 5.1.6 on 2025-03-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceMonitor', '0008_apilog_delete_pricehistory_transaction_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='vegetable_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='vegetable_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
