# Generated by Django 5.1.6 on 2025-03-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceMonitor', '0009_remove_transaction_vegetable_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
