# Generated by Django 5.1.6 on 2025-03-19 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceMonitor', '0010_apilog_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='api_log_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='PriceMonitor.apilog'),
        ),
    ]
