# Generated by Django 5.1.6 on 2025-03-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceMonitor', '0011_transaction_api_log_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tran_type',
            field=models.CharField(choices=[('add_vegetable', 'Add Vegetable'), ('update_price', 'Update Price'), ('delete_vegetable', 'Delete Vegetable'), ('add_user', 'Add User')], max_length=100),
        ),
    ]
