# Generated by Django 5.1.6 on 2025-03-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceMonitor', '0012_alter_transaction_tran_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apilog',
            old_name='request_method',
            new_name='method',
        ),
        migrations.RenameField(
            model_name='apilog',
            old_name='response_status',
            new_name='response_status_code',
        ),
        migrations.RemoveField(
            model_name='apilog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='apilog',
            name='request_path',
        ),
        migrations.AddField(
            model_name='apilog',
            name='url',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='request_body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='response_body',
            field=models.TextField(blank=True),
        ),
    ]
