# Generated by Django 5.1.6 on 2025-03-19 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PriceMonitor', '0013_rename_request_method_apilog_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='api_log_id',
        ),
    ]
