# Generated by Django 5.1.6 on 2025-03-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PriceMonitor', '0014_remove_transaction_api_log_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='file_metadata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='response_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
