# Generated by Django 5.1.6 on 2025-03-19 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PriceMonitor', '0015_apilog_file_metadata_alter_apilog_response_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APILog',
        ),
    ]
